### ISSUE TITLE
Error 500...but finally works after...

### ISSUE THREAD

**Issue by Fabrice61** [RichardDern/Cyca#32]
On a fresh installation (Ubuntu Server 20.04 LEMP) during the 1st launch of the web interface and just after validating my registration I got a 500 error...

I just relaunched the page by removing the /register and the application tells me that a verification email has just been sent to me.

I validate the link received by email and everything seems to work normally...

Nginx logs show no errors.

Are there any other logs I can give you?

Fabrice / Normandy / France

**Comment by RichardDern** [comment]
Hello fellow French citizen :) (Moselle / France)

Maybe in the storage/logs directory. You should have one file per day, you might get something.

I'm going to look at what could go wrong during registration.

Thanks for the feedback anyway !

**Comment by RichardDern** [comment]
After some investigations, it could be caused by improper files permissions.

Be sure to change the owner of the whole directory to www-data with:

```bash
chown -R www-data:www-data /path/to/cyca
```

After you grabbed the archive.

I will need to look further if that's not the problem because I couldn't reproduce it locally.

**Comment by Fabrice61** [comment]
OK, bon ce n'est pas grave, les permissions étaient OK, j'essaierai de reproduire mais comment te contacter car j'ai plein de questions et j'avoue que je suis un peu perdu devant l'interface, je n'ai pas compris l'ergonomie...

**Comment by RichardDern** [comment]
Tu peux me joindre à richard.github@getcyca.com
