### ISSUE TITLE
Installation procedure update

### ISSUE THREAD

**Issue by secnum** [RichardDern/Cyca#33]
On [Cyca installation procedure](https://www.getcyca.com/docs/native-installation/), you should add these PHP modules in order to get PHP composer installs the dependencies without error :

- php-curl
- php-mbstring
- php-xml

PHP composer indicates that "_Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested._"

You should tell users to install Supervisor at the beginning of the procedure.

**Comment by RichardDern** [comment]
Thanks for your feedback !

> PHP composer indicates that "Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested."

This is because Laravel's version used by Cyca still references the old Faker library for testing purposes. It is not a requirement to properly run Cyca and can safely be ignored.

I will update the docs accordingly to your other suggestions as you make a good point !

**Comment by RichardDern** [comment]
Done !
